---
- name: Install Python3 and pip (Amazon Linux / RHEL / CentOS)
  yum:
    name:
      - python3
      - python3-pip
      - python3-virtualenv 
    state: present
  when: ansible_os_family == "RedHat"
  become: yes


- name: Ensure Flask artifact filename
  ansible.builtin.set_fact:
    flask_artifact: "flask-app-{{ lookup('env','BUILD_NUMBER') }}.tar.gz"

- name: Download Flask artifact from S3
  amazon.aws.aws_s3:
    bucket: dual-app-artifacts
    object: "flask/{{ flask_artifact }}"
    dest: "/tmp/{{ flask_artifact }}"
    mode: get
    region: eu-west-2

- name: Ensure Flask app directory exists
  ansible.builtin.file:
    path: /opt/flask-app
    state: directory
    owner: "{{ ansible_user | default('ec2-user') }}"
    group: "{{ ansible_user | default('ec2-user') }}"
    mode: '0755'

- name: Extract Flask artifact
  ansible.builtin.unarchive:
    src: "/tmp/{{ flask_artifact }}"
    dest: /opt/flask-app
    remote_src: yes

- name: Create Python virtualenv
  ansible.builtin.command:
    cmd: python3 -m venv /opt/flask-app/venv
    creates: /opt/flask-app/venv/bin/activate

- name: Install Flask dependencies in virtualenv
  pip:
    requirements: /opt/flask-app/requirements.txt
    virtualenv: /opt/flask-app/venv
    virtualenv_python: python3

- name: Create systemd service for Flask
  copy:
    dest: /etc/systemd/system/flask.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      ExecStart=/opt/flask-app/venv/bin/python /opt/flask-app/app.py
      WorkingDirectory=/opt/flask-app
      Restart=always
      Environment=DB_HOST=localhost DB_NAME={{ db_name }} DB_USER={{ db_user }} DB_PASS={{ db_password }}

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Flask service
  systemd:
    name: flask
    state: started
    enabled: yes


