- name: Install Python3 and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Download Flask artifact from S3
  amazon.aws.aws_s3:
    bucket: dual-app-artifacts
    object: flask/flask-app-25.tar.gz
    dest: /tmp/flask-app-25.tar.gz
    mode: get    

- name: Ensure flask app directory exists
  ansible.builtin.file:
    path: /opt/flask-app
    state: directory
    owner: "{{ ansible_user | default('ec2-user') }}"
    group: "{{ ansible_user | default('ec2-user') }}"
    mode: '0755'


- name: Extract Flask artifact
  unarchive:
    src: "s3://dual-app-artifacts/flask/flask-app-{{ lookup('env','BUILD_NUMBER') }}.tar.gz"
    dest: /opt/flask-app
    remote_src: yes

- name: Install Flask dependencies
  pip:
    requirements: /opt/flask-app/requirements.txt

- name: Start Flask app with systemd
  copy:
    dest: /etc/systemd/system/flask.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      ExecStart=/usr/bin/python3 /opt/flask-app/app.py
      WorkingDirectory=/opt/flask-app
      Restart=always
      Environment=DB_HOST=localhost DB_NAME={{ db_name }} DB_USER={{ db_user }} DB_PASS={{ db_password }}

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Flask service
  systemd:
    name: flask
    state: started
    enabled: yes
