- name: Install PostgreSQL
  yum:
    name: postgresql-server
    state: present

- name: Initialize PostgreSQL DB
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Create DB user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "ALL"
