- name: Add PostgreSQL PGDG repository (Amazon Linux 2023)
  ansible.builtin.yum_repository:
    name: pgdg
    description: "PostgreSQL RPM Repository"
    baseurl: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/
    gpgcheck: yes
    gpgkey: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
    enabled: yes
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

- name: Install PostgreSQL 15 packages (Amazon Linux 2023)
  dnf:
    name:
      - postgresql15
      - postgresql15-server
      - postgresql15-contrib
      - postgresql15-devel
    state: present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

- name: Initialize PostgreSQL 15 database (Amazon Linux 2023)
  command: "/usr/bin/postgresql-setup --initdb"
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

- name: Ensure PostgreSQL service is running (Amazon Linux 2023)
  service:
    name: postgresql
    state: started
    enabled: yes
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

- name: Ensure python3 and pip3 are installed (Amazon Linux / RHEL)
  ansible.builtin.yum:
    name:
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"  

- name: Ensure psycopg2 is installed
  ansible.builtin.pip:
    name: psycopg2-binary
    state: present
    executable: pip3



- name: Create database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"

- name: Create DB user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present

- name: Grant privileges to DB user
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    type: database
    privs: ALL
    state: present

