- hosts: web
  become: yes
  vars_files:
    - vault.yaml
  vars:
    flask_port: 5000
    node_port: 3000
    db_name: shared_db
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"

  roles:
    - postgres
    - flask
    - node.js