---
- name: Add NodeSource repo for Node.js 20
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
  args:
    warn: false
  become: yes

- name: Install Node.js
  yum:
    name: nodejs
    state: present
  become: yes

- name: Set Node.js artifact filename
  ansible.builtin.set_fact:
    node_artifact: "node-app-{{ lookup('env','BUILD_NUMBER') }}.tar.gz"

- name: Download Node.js artifact from S3
  amazon.aws.aws_s3:
    bucket: dual-app-artifacts
    object: "node/{{ node_artifact }}"
    dest: "/tmp/{{ node_artifact }}"
    mode: get
    region: eu-west-2

- name: Ensure Node.js app directory exists
  ansible.builtin.file:
    path: /opt/node-app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Extract Node.js artifact
  ansible.builtin.unarchive:
    src: "/tmp/{{ node_artifact }}"
    dest: /opt/node-app
    remote_src: yes

- name: Install Node.js dependencies
  ansible.builtin.command:
    cmd: npm install
    chdir: /opt/node-app
  become: yes
  become_user: ec2-user

- name: Create .env file for Node.js
  ansible.builtin.copy:
    dest: /opt/node-app/.env
    content: |
      DB_HOST=localhost
      DB_NAME={{ db_name }}
      DB_USER={{ db_user }}
      DB_PASSWORD={{ db_password }}
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Create systemd service for Node.js
  ansible.builtin.copy:
    dest: /etc/systemd/system/node.service
    content: |
      [Unit]
      Description=Node.js App
      After=network.target

      [Service]
      User=ec2-user
      Group=ec2-user
      WorkingDirectory=/opt/node-app
      ExecStart=/usr/bin/node /opt/node-app/server.js
      Restart=always
      EnvironmentFile=/opt/node-app/.env

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start Node service
  ansible.builtin.systemd:
    name: node
    state: started
    enabled: yes
  become: yes

