---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Flask app
  systemd:
    name: flask-app
    state: restarted
    enabled: yes

- name: Restart Node.js app
  systemd:
    name: node-app
    state: restarted
    enabled: yes

